add_newline = true

format = """
󱩡 \
$os\
$directory\
$rust\
$lua\
$java\
$conda\
$container\
$c\
$go\
$nodejs\
$python\
$ruby\
$shell\
$swift\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$line_break\
$character\
"""

[character]
success_symbol = '[  ](bold green)'
error_symbol = "[  ](bold red)"
