# Yttrium.RBCUSTOM

spacing = 2
padding = 0
hide_ascii = false
prefer_small_ascii = true
separator = ""
key_color = "#FF6500"
separator_color = "#FFC100"

[bar]
glyph = "||"
symbol_open = '['
symbol_close = ']'
hide_delimiters = true
visible = true

[box]
title = "Yttrium.RBCUSTOM"
border = "Double"
visible = false

[box.inner_margin]
x = 2
y = 0

[custom_ascii]
color = "#FF6500"
path = "~/.config/macchina/ascii.txt"

[randomize]
key_color = false
separator_color = false

[keys]
os = "OS"
distro = "DISTRO"
terminal = "TERM"
shell = "SHELL"
packages = "PKGS"
uptime = "UPTIME"
battery = "BATTERY"
memory = "MEMORY"
cpu_load = "CPU"
